version: '2'

volumes:
  geodropinfiles:
  geodropinlogos:
  mongo_db:
  oracle_db:
  ogr2ogr_shapefiles:
  ogr2ogr_tnsadmin:

services:
  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - proxy
    volumes:
      - base_certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - gdi-base
    
  gdi.web:
    restart: always
    image: idgis/geodropin:${GDI_VERSION}
    environment:
      - MAIL_URL=smtp://${GDI_EMAIL_USER}:${GDI_EMAIL_PASSWORD}@${GDI_EMAIL_SERVER}:${GDI_EMAIL_PORT}
      - MONGO_URL=mongodb://gdi.db/geodropin
      - ROOT_URL=http://${DOMAIN_PREFIX}geodropin${DOMAIN_SUFFIX}:${HTTP_PORT}
      - LETSENCRYPT_HOST=${DOMAIN_PREFIX}geodropin${DOMAIN_SUFFIX}
      - LETSENCRYPT_EMAIL=admin@geopublisher.nl
    volumes:
      - geodropinfiles:/var/lib/geodropinfiles
      - geodropinlogos:/var/lib/geodropinlogos
    networks:
      - gdi-base

  gdi.db:
    restart: always
    image: mongo:3.2.11
    volumes:
      - mongo_db:/data/db
    networks:
      - gdi-base
      
  oracle.metadata:
    image: idgis/oracle-metadata
    networks:
      - gdi-base
  
  oracle:
    build: oracle
    restart: always
    volumes:
      - oracle_db:/u01/app/oracle
    networks:
      - gdi-base
  
  ogr2ogr:
    build: ogr2ogr
    tty: true
    environment:
      - LD_LIBRARY_PATH=/opt/instantclient_12_1
      - TNS_ADMIN=/opt/instantclient_12_1
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/instantclient_12_1
    volumes:
      - ogr2ogr_shapefiles:/var/lib/shapefiles
      - ogr2ogr_tnsadmin:/opt/instantclient_12_1
    networks:
      - gdi-base
      
networks:
  gdi-base:
    external: true