version: '2'

volumes:
  base_certs:
  base_vhost:
  base_html:

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "136.243.17.245:80:80"
      - "136.243.17.245:443:443"
    volumes:
      - base_certs:/etc/nginx/certs:ro
      - base_vhost:/etc/nginx/vhost.d
      - base_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - base_certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: gdi_proxy