version: '2'

services:
  
  geoserver:
    image: idgis/geopublisher_geoserver:${PUB_VERSION}
    restart: always
    environment:
      - GEOSERVER_USER=admin
      - GEOSERVER_PASSWORD=${PUB_GEOSERVER_PASSWORD}
      - PG_HOST=pub.db
      - PG_PORT=5432
      - PG_DBNAME=publisher
      - PG_USER=publisher
      - PG_PASSWORD=${PUB_PG_PASSWORD}
      - ZOOKEEPER_HOSTS=zookeeper
      - SERVICE_DOMAIN=${DOMAIN_PREFIX}${DOMAIN_SUFFIX}
      - JAVA_OPTS=-Xmx1g -Duser.timezone=${TIME_ZONE}
      
  viewer:
    image: idgis/geopublisher_viewer:${PUB_VIEWER_VERSION}
    restart: always
    environment:
      - VIEWER_USERNAME=admin
      - VIEWER_PASSWORD=${PUB_GEOSERVER_PASSWORD}
      - VIEWER_CENTERS=${PUB_VIEWER_CENTERS}
      - JAVA_OPTS=-Xmx32M -Duser.timezone=${TIME_ZONE}