version: '2'

volumes:
  pub_db_data:
  pub_db_logs:
  pub_service_raster:
  pub_service_sslconf:
  pub_provider_conf:
  pub_geoserver_staging_data:
  pub_geoserver_public_data:

services:
  pub.db:
    image: idgis/geopublisher_database:${PUB_VERSION}
    restart: always
    environment:
      - PG_USER=publisher
      - PG_PASSWORD=${PUB_PG_PASSWORD}
    volumes:
      - pub_db_data:/var/lib/postgresql
      - pub_db_logs:/var/log/postgresql
      
  pub.db.init:
    build: pub-db-init
    depends_on:
      - pub.db
    environment:
      - PG_HOST=pub.db
      - PG_PORT=5432
      - PG_DBNAME=publisher
      - PG_USER=publisher
      - PG_PASSWORD=${PUB_PG_PASSWORD}
      - DATASOURCE_0=geodropin-vector,Vectordata
      - ENVIRONMENT_0=geoserver-public,Publieke services,false,http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/public/geoserver/,false
      
  pub.provider:
    image: idgis/geopublisher_provider:${PUB_VERSION}
    restart: always
    environment:
      - JAVA_OPTS=-Xmx256M -Duser.timezone=${TIME_ZONE}
    volumes:
      - pub_provider_conf:/etc/geo-publisher/provider
    
  pub.service:
    image: idgis/geopublisher_service:${PUB_VERSION}
    restart: always
    depends_on:
      - pub.db
    environment:
      - PG_HOST=pub.db
      - PG_PORT=5432
      - PG_DBNAME=publisher
      - PG_USER=publisher
      - PG_PASSWORD=${PUB_PG_PASSWORD}
      - GEOSERVER_USER=admin
      - GEOSERVER_PASSWORD=${PUB_GEOSERVER_PASSWORD}
      - AKKA_HOSTNAME=pub.service
      - AKKA_LOGLEVEL=DEBUG
      - ZOOKEEPER_HOSTS=zookeeper
      - METADATA_URL_PREFIX=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/metadata/dataset/
      - SSL_PRIVATE_KEYSTORE=/etc/geo-publisher/ssl/private.jks
      - SSL_PRIVATE_KEYSTORE_PASSWORD=harvester
      - SSL_TRUSTED_KEYSTORE=/etc/geo-publisher/ssl/trusted.jks
      - SSL_TRUSTED_KEYSTORE_PASSWORD=harvester
      - RASTER_DIR=/var/lib/geo-publisher/raster
      - INCLUDE_CONFIDENTIAL=${PUB_INCLUDE_CONFIDENTIAL}
      - JAVA_OPTS=-Xmx256M -Duser.timezone=${TIME_ZONE}
    volumes:
      - pub_service_raster:/var/lib/geo-publisher/raster
      - pub_service_sslconf:/etc/geo-publisher/ssl
    
  pub.web:
    image: idgis/geopublisher_web:${PUB_VERSION}
    restart: always
    depends_on:
      - pub.service
    environment:
      - ADMIN_CONTEXT=/admin
      - AKKA_HOSTNAME=pub.web
      - SERVICE_HOST=pub.service
      - ADMIN_PASSWORD=${PUB_ADMIN_PASSWORD}
      - GEOSERVER_DOMAIN=${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/staging
      - DATASET_METADATA_URL_PREFIX=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/metadata/dataset/
      - SERVICE_METADATA_URL_PREFIX=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/metadata/service/
      - CLIENT_LOGO=${PUB_CLIENT_LOGO}
      - CLIENT_URL=${PUB_CLIENT_URL}
      - PREVIEW_BBOX=${PUB_PREVIEW_BBOX}
      - METADATA_BBOX=${PUB_METADATA_BBOX}
      - JAVA_OPTS=-Xmx32M -Duser.timezone=${TIME_ZONE}"
      - METADATA_STYLESHEET_URL_PREFIX=/metadata/stylesheets/
      - LETSENCRYPT_HOST=${DOMAIN_PREFIX}${DOMAIN_SUFFIX}
      - LETSENCRYPT_EMAIL=admin@geopublisher.nl
    
  pub.metadata:
    image: idgis/geopublisher_metadata:${PUB_VERSION}
    restart: always
    depends_on:
      - pub.db  
    environment:
      - PG_HOST=pub.db
      - PG_PORT=5432
      - PG_DBNAME=publisher
      - PG_USER=publisher
      - PG_PASSWORD=${PUB_PG_PASSWORD}
      - VIEWER_URL_PREFIX_PUBLIC=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/public/viewer
      - VIEWER_URL_PREFIX_SECURE=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/secure/viewer
      - VIEWER_URL_PREFIX_WMSONLY=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/wmsonly/viewer
      - TRUSTED_HEADER=GeoPublisher-trusted
      - METADATA_HOST=${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}
      - JAVA_OPTS=-Xmx128M -Duser.timezone=${TIME_ZONE}
      - METADATA_BBOX=${PUB_METADATA_BBOX}
      - STYLESHEET_PREFIX=/metadata/stylesheets/
      - DOWNLOAD_URL_DISPLAY=${PUB_DOWNLOAD_URL_DISPLAY}
      - INCLUDE_SOURCE_DATASET_METADATA=${PUB_INCLUDE_SOURCE_DATASET_METADATA}
      - LETSENCRYPT_HOST=${DOMAIN_PREFIX}${DOMAIN_SUFFIX}
      - LETSENCRYPT_EMAIL=admin@geopublisher.nl
    
  pub.geoserver.staging:
    extends:
      file: geo-publisher-commons.yml
      service: geoserver
    environment:
      - SERVICE_IDENTIFICATION=geoserver-staging
      - LETSENCRYPT_HOST=${DOMAIN_PREFIX}${DOMAIN_SUFFIX}
      - LETSENCRYPT_EMAIL=admin@geopublisher.nl
      - PROXY_BASE_URL=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/staging/geoserver/
    volumes:
      - pub_service_raster:/var/lib/geo-publisher/raster
      - pub_geoserver_staging_data:/var/lib/geo-publisher/geoserver
    
  pub.viewer.staging:
    extends:
      file: geo-publisher-commons.yml
      service: viewer
    depends_on:
      - pub.geoserver.staging
    environment:
      - VIEWER_ENVIRONMENT_URL=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/staging/geoserver/
      - VIEWER_CONTEXT=/staging/viewer
      - LETSENCRYPT_HOST=${DOMAIN_PREFIX}${DOMAIN_SUFFIX}
      - LETSENCRYPT_EMAIL=admin@geopublisher.nl
    external_links:
      - proxy:${DOMAIN_PREFIX}${DOMAIN_SUFFIX}

  pub.geoserver.public:
    extends:
      file: geo-publisher-commons.yml
      service: geoserver
    environment:
      - SERVICE_IDENTIFICATION=geoserver-public
      - LETSENCRYPT_HOST=${DOMAIN_PREFIX}${DOMAIN_SUFFIX}
      - LETSENCRYPT_EMAIL=admin@geopublisher.nl
      - PROXY_BASE_URL=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/public/geoserver/
    volumes:
      - pub_service_raster:/var/lib/geo-publisher/raster
      - pub_geoserver_public_data:/var/lib/geo-publisher/geoserver
    
  pub.viewer.public:
    extends:
      file: geo-publisher-commons.yml
      service: viewer
    depends_on:
      - pub.geoserver.public
    environment:
      - VIEWER_ENVIRONMENT_URL=http://${DOMAIN_PREFIX}${DOMAIN_SUFFIX}:${HTTP_PORT}/public/geoserver/
      - VIEWER_CONTEXT=/public/viewer
      - LETSENCRYPT_HOST=${DOMAIN_PREFIX}${DOMAIN_SUFFIX}
      - LETSENCRYPT_EMAIL=admin@geopublisher.nl
    external_links:
      - proxy:${DOMAIN_PREFIX}${DOMAIN_SUFFIX}

networks:
  default:
    external:
      name: gdi