version: '2'

volumes:
  geodropinfiles:
  geodropinlogos:
  mongo_db:
  oracle_db:
  geodropin_shapefiles:

services:
  gdi.web:
    restart: always
    image: idgis/geodropin:0.1.0
    environment:
      - MONGO_URL=mongodb://gdi.db/geodropin
      - ROOT_URL=http://acc-geodropin.geopublisher.nl
      - VIRTUAL_HOST=acc-geodropin.geopublisher.nl
      - LETSENCRYPT_HOST=acc-geodropin.geopublisher.nl
      - LETSENCRYPT_EMAIL=admin@geopublisher.nl
    volumes:
      - geodropinfiles:/var/lib/geodropinfiles
      - geodropinlogos:/var/lib/geodropinlogos

  gdi.db:
    restart: always
    image: mongo:3.2.11
    volumes:
      - mongo_db:/data/db
  
  gdi.oracle:
    restart: always
    image: wnameless/oracle-xe-11g:latest
    ports:
      - "136.243.17.245:49160:22"
      - "136.243.17.245:49161:1521"
    volumes:
      - oracle_db:/u01/app/oracle
  
  gdi.ogr2ogr:
    image: idgis/ogr2ogr
    tty: true
    volumes:
      - geodropin_shapefiles:/var/lib/shapefiles
      
networks:
  default:
    external:
      name: gdi_proxy