version: '2'

volumes:
  base_certs:
  base_vhost:
  base_html:

services:
  proxy:
    restart: always
    build: nginx-dev
    ports:
      - "${IP_ADDR}:${HTTP_PORT}:${HTTP_PORT}"
      - "${IP_ADDR}:${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - base_certs:/etc/nginx/certs:ro
      - base_vhost:/etc/nginx/vhost.d
      - base_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - gdi-base